#!/usr/bin/env bash

MODE="${1:-sink}"

ID_FILE="/tmp/osd-$MODE.id"
TIMEOUT=3000

# drain stdin only if piped
[[ -p /dev/stdin ]] && cat >/dev/null

source ~/.config/niri/scripts/utils

case "$MODE" in
  sink)
    NODE="@DEFAULT_AUDIO_SINK@"
    TITLE="Volume"

    INFO=$(wpctl get-volume "$NODE")
    VOL=$(echo "$INFO" | awk '{printf "%d", $2 * 100}')
    VOL_BAR=$(progress_bar "$VOL" 100 40)

    if echo "$INFO" | grep -q MUTED; then
      notify_replace "󰸈 $TITLE ${VOL}% (Muted)" "$VOL_BAR"
    else
      notify_replace "󰕾 $TITLE ${VOL}%" "$VOL_BAR"
    fi
    ;;
  source)
    NODE="@DEFAULT_AUDIO_SOURCE@"
    TITLE="Microphone"

    INFO=$(wpctl get-volume "$NODE")
    VOL=$(echo "$INFO" | awk '{printf "%d", $2 * 100}')
    VOL_BAR=$(progress_bar "$VOL" 100 40)

    if echo "$INFO" | grep -q MUTED; then
      notify_replace "󰍭 $TITLE ${VOL}% (Muted)" "$VOL_BAR"
    else
      notify_replace "󰍬 $TITLE ${VOL}%" "$VOL_BAR"
    fi
    ;;
  brightness)
    CUR=$(brightnessctl get)
    MAX=$(brightnessctl max)
    PCT=$(( CUR * 100 / MAX ))
    PCT_BAR=$(progress_bar "$PCT" 100 40)

    notify_replace "☀ Brightness ${PCT}%" "$PCT_BAR"
    ;;
  *)
    exit 0
    ;;
esac
