#!/bin/bash

CONFIG_DIR="$HOME/.config/niri"
LINK="$CONFIG_DIR/keyboard.kdl"
DEFAULT="$CONFIG_DIR/scripts/keyboard-default.kdl"
MOD="$CONFIG_DIR/scripts/keyboard-remap.kdl"

source ~/.config/niri/scripts/utils

# Check if the link exists and where it points
if [ -L "$LINK" ]; then
    CURRENT_TARGET=$(readlink "$LINK")
    if [ "$CURRENT_TARGET" = "$DEFAULT" ]; then
        ln -sf "$MOD" "$LINK"
        notify_replace "󰥻 ON" "Using Remap Keyboard"
    else
        ln -sf "$DEFAULT" "$LINK"
        notify_replace "󰹋 OFF" "Using Default Keyboard"
    fi
else
    # If default doesn't exist, create it pointing to default
    ln -sf "$DEFAULT" "$LINK"
    notify "󰹋 Using Default Keyboard"
fi
