# -*- conf -*-
# default config: /etc/xdg/foot/foot.ini

# preferred: zenburn, tempus-rift, apprentice, molokai, monokai-pro, tempus-classic
include=/usr/share/foot/themes/zenburn

term=xterm-256color
font=Cascadia Code:size=10
pad=8x8

[url]
launch=xdg-open ${url}

[colors-dark]
background=000000
